### ISSUE TITLE
Issue when running

### ISSUE THREAD

**Issue by garrettdotnet** [Myldero/1.12-to-1.13#1]
Hello,

I've tried running this script on multiple machines, following the run syntax command you provided.
It will not execute and I always receive an error message. 

Here's the current error message I get upon run:

python run.py
  File "run.py", line 45
    default, *states = blockstates_other[block].split()

Let me know when this is fixed, thanks!
Garrett

**Comment by Myldero** [comment]
You are perhaps using Python 2. This converter is made specifically for Python 3. Try with Python 3.5+
