### ISSUE TITLE
What do I do for the name space

### ISSUE THREAD

**Issue by Swanlet** [Myldero/1.12-to-1.13#2]
okay so im not very computer savy, for the thing where theres the giant black box, do you just have to paste the location of the folder with the world, I tried that and nothing happended, what exactly do I have to type for a Name Space or whatever to make the files go in there

**Comment by Myldero** [comment]
First you have to put in the filepath. If it's a singleplayer world, It's in the .minecraft folder. The filepath could look like this "C:\Users\\(Your username)\AppData\Roaming\\.minecraft\saves\\(World Name)".
The namespace is the namespace of your datapack. Indeed there should just be an option to use the old namespaces, but then you would need a namespace for each of them. A namespace is the name you type before the colon when running a function.
