### ISSUE TITLE
Closes instantly

### ISSUE THREAD

**Issue by bluecommands** [Myldero/1.12-to-1.13#3]
I clicked on run.py and it opened and all it did was ask me to import nbt in my terminal which I did as instructed but now when I open it, the program just closes instantly. Before I just double clicked on it but when running it in the python shell I get this error:

**_Traceback (most recent call last):
** IDLE Internal Exception: 
  File "C:\Users\Peter\AppData\Local\Programs\Python\Python37-32\lib\idlelib\run.py", line 474, in runcode
    exec(code, self.locals)
  File "C:\Users\Peter\Downloads\1.12-to-1.13-master\run.py", line 24, in <module>
    itemvalues = dict(line.rstrip().split(":", 1) for line in open(os.path.join(".", "itemvalues.txt"), 'r'))
ValueError: dictionary update sequence element #70 has length 1; 2 is required_**

Have I done something wrong or is this a bug?

**Comment by Myldero** [comment]
It was indeed a bug. You can easily fix it yourself by going into itemvalues.txt and removing the last few empty lines.
