### ISSUE TITLE
.py file 

### ISSUE THREAD

**Issue by NightHowler72** [Myldero/1.12-to-1.13#4]
Whenever I try to open the .py files, (Commands.py and run.py) It always opens them in my notepad instead of Python, do you know anyway to fix it? I have the latest version of python downloaded.

**Comment by Myldero** [comment]
You should be able to right-click, choose "Open With" and then pick "Python".
If that does not work, you'll have to go into the folder you installed Python to and find the python.exe file. Get the path of that file. E.g. C:\Users\\(Username)\AppData\Local\Programs\Python\Python37-32\python.exe
Then you have to find the folder in which you have the program. E.g. C:\Users\\(Username)\Desktop\1.12-to-1.13-master\run.py
Then you can open cmd by pressing CTRL + R and typing in "cmd".
Then you type `<path1> <path2>`
