### ISSUE TITLE
Index Out of Range While Converting Functions

### ISSUE THREAD

**Issue by ThickPropheT** [Myldero/1.12-to-1.13#5]
Not very familiar with Python, but doesn't look like this error message gives much to go on. I have a LOT of mcfunctions. Using Beyond Compare, I can see about which file the conversion broke on. I'll attach the pre and post conversion files if that helps.

**Error**
Path to world folder: F:\Games\\.minecraft\saves\A LAN'd of Mystery
Datapack namespace [a-z0-9_-]: conversion_pack
Moving directories
Converting functions
Traceback (most recent call last):
  File "F:\Games\.minecraft\utilities\1.12-to-1.13-master\run.py", line 1504, in <module>
    memory += convert(line.rstrip())
  File "F:\Games\.minecraft\utilities\1.12-to-1.13-master\run.py", line 1048, in convert
    if tp_self == True and re.findall(r'^tp @s', executelist[-1]):
IndexError: list index out of range

**Function Files**
[pre-conversion.zip](https://github.com/Myldero/1.12-to-1.13/files/2320157/pre-conversion.zip)
[post-conversion.zip](https://github.com/Myldero/1.12-to-1.13/files/2320161/post-conversion.zip)

**Comment by Myldero** [comment]
Thanks for your report. I've fixed the issue. You can go ahead and redownload the program and try again. I've also added better error catching so the program won't just crash if a problem like this occurs again.
