### ISSUE TITLE
cant execute

### ISSUE THREAD

**Issue by MatheusAssisNeves** [Myldero/1.12-to-1.13#6]
Im getting this error every time i open "run.py"

Run "C:\Users\USERNAME\AppData\Local\Programs\Python\Python37-32\python.exe -m pip install nbt" as administrator in terminal/cmd

**Comment by Myldero** [comment]
Follow the instructions.
If you're on Windows, press Windows-key + R, and type cmd. Press Enter.
Then copy that line ("C:\Users\USERNAME\AppData\Local\Programs\Python\Python37-32\python.exe -m pip install nbt") into there and press enter. That should install a package for you. When it's done, you can try to open run.py again.
