### ISSUE TITLE
Cannot execute.

### ISSUE THREAD

**Issue by Bombardier-C-Kram** [Myldero/1.12-to-1.13#8]
I already installed nbt.

![Screenshot from 2020-05-31 07-56-29](https://user-images.githubusercontent.com/51411143/83351708-62c56b00-a314-11ea-8102-51a50bd2680d.png)
I get a lot of errors tho...

**Comment by Bombardier-C-Kram** [comment]
Btw its python 3.8.2

**Comment by AlexanderSkovsende** [comment]
I haven't tested this in python 3.8. It seems that it runs into an error when importing the nbt module. Perhaps change the line `from nbt.nbt import *` into `from nbt import *`.
